# Generated by Django 4.2.3 on 2023-08-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('number', models.CharField(default=False, max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('middlename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/images')),
                ('fathername', models.CharField(max_length=255)),
                ('grandfather', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('married_status', models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'Unmarried'), ('Divorse', 'Divorse'), ('Widow', 'Widow')], default='UnMarried', max_length=50)),
                ('pannum', models.CharField(max_length=20)),
                ('nationality', models.CharField(choices=[('Nepalies', 'Nepalies'), ('Other', 'Other')], default='Nepalies', max_length=50)),
                ('citizenshipnumber', models.CharField(max_length=50)),
                ('citizen_issued_district', models.CharField(max_length=50)),
                ('citizen_issued_date', models.DateField()),
                ('front_photo', models.ImageField(upload_to='citizen/front')),
                ('back_photo', models.ImageField(upload_to='citizen/back')),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_issued_date', models.DateField()),
                ('passport_issued_place', models.CharField(max_length=100)),
                ('pass_front_photo', models.ImageField(upload_to='passport/front')),
                ('pass_back_photo', models.ImageField(upload_to='passport/back')),
                ('other_card', models.CharField(max_length=100)),
                ('other_card_number', models.CharField(max_length=20)),
                ('other_card_issued_date', models.DateField()),
                ('other_card_issued_authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='know.person')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_relation', models.CharField(max_length=100)),
                ('f_fullname', models.CharField(max_length=100)),
                ('f_remarks', models.CharField(max_length=150)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='know.person')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=10)),
                ('zone', models.CharField(max_length=40)),
                ('provience', models.CharField(choices=[('bagmati', 'Bagmati'), ('koshi', 'Koshi'), ('karnali', 'Karali'), ('madhesh', 'Madhesh'), ('ghandaki', 'Ghandaki'), ('lumbini', 'Lumbini'), ('sudherpachim', 'Sudherpachim')], max_length=50)),
                ('district', models.CharField(max_length=75)),
                ('muni_vdc', models.CharField(max_length=75)),
                ('house_no', models.CharField(max_length=10)),
                ('ward_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('tel_n0', models.CharField(blank=True, max_length=10)),
                ('post_box', models.CharField(max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='know.person')),
            ],
        ),
    ]
