# Generated by Django 4.2.3 on 2023-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0002_person_email_person_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other_card_back',
            field=models.ImageField(default='', upload_to='other/back'),
        ),
        migrations.AddField(
            model_name='person',
            name='other_card_front',
            field=models.ImageField(default='', upload_to='other/front'),
        ),
    ]
