# Generated by Django 4.2.3 on 2023-08-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0003_person_other_card_back_person_other_card_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='l_image',
            field=models.ImageField(default='', upload_to='location/image'),
        ),
    ]
