# Generated by Django 4.2.3 on 2023-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0004_address_l_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middlename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_card',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_card_back',
            field=models.ImageField(blank=True, default='', upload_to='other/back'),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_card_front',
            field=models.ImageField(blank=True, default='', upload_to='other/front'),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_card_issued_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_card_issued_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
