# Generated by Django 4.2.3 on 2023-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0005_alter_person_middlename_alter_person_other_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='back_photo',
            field=models.ImageField(blank=True, upload_to='citizen/back'),
        ),
        migrations.AlterField(
            model_name='person',
            name='front_photo',
            field=models.ImageField(blank=True, upload_to='citizen/front'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/images'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pass_back_photo',
            field=models.ImageField(blank=True, upload_to='passport/back'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pass_front_photo',
            field=models.ImageField(blank=True, upload_to='passport/front'),
        ),
    ]
