# Generated by Django 4.2.3 on 2023-08-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0006_alter_person_back_photo_alter_person_front_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='back_photo',
            field=models.ImageField(upload_to='citizen/back'),
        ),
        migrations.AlterField(
            model_name='person',
            name='front_photo',
            field=models.ImageField(upload_to='citizen/front'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='photos/images'),
        ),
    ]
