# Generated by Django 4.2.3 on 2023-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0007_alter_person_back_photo_alter_person_front_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('both', 'Both')], max_length=10),
        ),
    ]
