# Generated by Django 4.2.3 on 2023-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0010_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='Bank_name',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='account',
            new_name='account_no',
        ),
        migrations.AddField(
            model_name='bank',
            name='accounttype',
            field=models.CharField(default='Saving', max_length=15),
        ),
    ]
